import { useState, useEffect } from 'react';
// These will be generated by Wails on first build
// @ts-ignore
import { TestDatabase, TestAPI, SaveConfig, StartSync, GetConfig, GetState } from "../../wailsjs/go/main/App";

export default function App() {
  const [step, setStep] = useState(1);
  const [apiKey, setApiKey] = useState('');
  const [apiUrl, setApiUrl] = useState('https://api.peoplein.com');
  const [mdbPath, setMdbPath] = useState('C:\\Program Files (x86)\\eSSL\\eTimeTrackLite\\eTimeTrackLite1.mdb');
  const [machineName, setMachineName] = useState('Relay-1');
  
  const [apiTesting, setApiTesting] = useState(false);
  const [apiSuccess, setApiSuccess] = useState<boolean | null>(null);

  const [dbTesting, setDbTesting] = useState(false);
  const [dbSuccess, setDbSuccess] = useState<any>(null);

  const [isSyncing, setIsSyncing] = useState(false);
  const [lastSyncId, setLastSyncId] = useState(0);

  useEffect(() => {
    // Attempt to load existing config on boot
    GetConfig().then((cfg: any) => {
      if (cfg && cfg.apiKey) {
        setApiKey(cfg.apiKey);
        setApiUrl(cfg.apiUrl);
        setMdbPath(cfg.mdbPath);
        setMachineName(cfg.machineName);
        setStep(5); // Jump to dashboard if already configured
      }
    }).catch(() => {});
  }, []);

  const handleTestApi = async () => {
    setApiTesting(true);
    try {
      await TestAPI(apiUrl, apiKey, machineName);
      setApiSuccess(true);
    } catch (err) {
      setApiSuccess(false);
    }
    setApiTesting(false);
  };

  const handleTestDb = async () => {
    setDbTesting(true);
    try {
      const result = await TestDatabase(mdbPath);
      setDbSuccess(result);
    } catch (err) {
      setDbSuccess(false);
    }
    setDbTesting(false);
  };

  const handleStartSync = async () => {
    try {
      await SaveConfig({
        apiKey,
        apiUrl,
        mdbPath,
        machineName,
        syncIntervalMinutes: 5
      });
      await StartSync();
      setIsSyncing(true);
      setStep(5);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      <header className="bg-white border-b border-slate-200 px-6 py-4 flex items-center shadow-sm">
        <div className="h-8 w-8 bg-blue-600 rounded-lg flex items-center justify-center text-white font-bold mr-3 shadow-sm">
          P
        </div>
        <h1 className="text-xl font-bold text-slate-800 tracking-tight">PeopleIN Relay</h1>
      </header>

      <main className="flex-1 flex items-center justify-center p-8">
        <div className="bg-white rounded-2xl shadow-xl border border-slate-100 max-w-2xl w-full overflow-hidden">
          {/* Progress Bar */}
          {step < 5 && (
            <div className="flex border-b border-slate-100">
              {[1,2,3,4].map((s) => (
                <div key={s} className={`flex-1 h-1.5 ${step >= s ? 'bg-blue-500' : 'bg-slate-100'}`} />
              ))}
            </div>
          )}

          <div className="p-8">
            {step === 1 && (
              <div className="text-center py-8">
                <div className="inline-flex items-center justify-center w-20 h-20 bg-blue-50 text-blue-600 rounded-full mb-6">
                  <svg className="w-10 h-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <h2 className="text-3xl font-extrabold text-slate-800 mb-4">Connect eTimeTrackLite</h2>
                <p className="text-slate-500 mb-8 max-w-md mx-auto text-lg leading-relaxed">
                  Automate attendance synchronization securely from your local network directly to PeopleIN.
                </p>
                <button 
                  onClick={() => setStep(2)}
                  className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg shadow-md transition-colors text-lg"
                >
                  Get Started
                </button>
              </div>
            )}

            {step === 2 && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-2xl font-bold text-slate-800 mb-2">API Credentials</h2>
                  <p className="text-slate-500">Enter your PeopleIN API credentials to authorize this relay.</p>
                </div>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">API Key</label>
                    <input 
                      type="password" 
                      value={apiKey}
                      onChange={e => setApiKey(e.target.value)}
                      className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                      placeholder="sk_live_..."
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">API URL</label>
                    <input 
                      type="text" 
                      value={apiUrl}
                      onChange={e => setApiUrl(e.target.value)}
                      className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                    />
                  </div>
                </div>

                <div className="pt-4 flex items-center justify-between">
                  <button 
                    onClick={handleTestApi}
                    disabled={apiTesting || !apiKey}
                    className="text-blue-600 font-medium hover:text-blue-700 disabled:opacity-50"
                  >
                    {apiTesting ? 'Testing...' : 'Test Connection'}
                  </button>
                  
                  <div className="flex items-center gap-3">
                    {apiSuccess === true && <span className="text-emerald-600 font-medium flex items-center gap-1"><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg> Connected</span>}
                    {apiSuccess === false && <span className="text-red-600 font-medium">Failed</span>}
                    <button 
                      onClick={() => setStep(3)}
                      disabled={!apiSuccess}
                      className="bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
                    >
                      Next Step
                    </button>
                  </div>
                </div>
              </div>
            )}

            {step === 3 && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-2xl font-bold text-slate-800 mb-2">Select Database</h2>
                  <p className="text-slate-500">Point the relay to your eTimeTrackLite MDB file.</p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">MDB File Path</label>
                  <input 
                    type="text" 
                    value={mdbPath}
                    onChange={e => setMdbPath(e.target.value)}
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all font-mono text-sm"
                  />
                </div>

                <div className="pt-4 flex items-center justify-between">
                  <button 
                    onClick={handleTestDb}
                    disabled={dbTesting || !mdbPath}
                    className="text-blue-600 font-medium hover:text-blue-700 disabled:opacity-50"
                  >
                    {dbTesting ? 'Testing...' : 'Test Database'}
                  </button>

                  <button 
                    onClick={() => setStep(4)}
                    disabled={!dbSuccess}
                    className="bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
                  >
                    Confirm
                  </button>
                </div>

                {dbSuccess && dbSuccess.success && (
                  <div className="mt-6 p-4 bg-emerald-50 border border-emerald-100 rounded-lg">
                    <h4 className="text-emerald-800 font-semibold flex items-center gap-2 mb-3">
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                      Database Connected
                    </h4>
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <span className="block text-emerald-600/80">Employees</span>
                        <span className="font-medium text-emerald-900">{dbSuccess.employeeCount}</span>
                      </div>
                      <div>
                        <span className="block text-emerald-600/80">Attendance Records</span>
                        <span className="font-medium text-emerald-900">{dbSuccess.attendanceCount}</span>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}

            {step === 4 && (
              <div className="text-center py-8">
                <div className="inline-flex items-center justify-center w-20 h-20 bg-emerald-50 text-emerald-600 rounded-full mb-6">
                  <svg className="w-10 h-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <h2 className="text-3xl font-extrabold text-slate-800 mb-4">You're All Set!</h2>
                <p className="text-slate-500 mb-8 max-w-md mx-auto text-lg">
                  The relay is configured and ready to synchronize attendance records automatically every 5 minutes.
                </p>
                <button 
                  onClick={handleStartSync}
                  className="bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-3 px-8 rounded-lg shadow-md transition-colors text-lg"
                >
                  Start Synchronization
                </button>
              </div>
            )}

            {step === 5 && (
              <div className="space-y-6">
                <div className="flex items-center justify-between mb-8">
                  <h2 className="text-2xl font-bold text-slate-800">Relay Dashboard</h2>
                  <div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-50 text-emerald-700 rounded-full text-sm font-medium border border-emerald-200">
                    <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></div>
                    Service Active
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-6">
                  <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
                    <h3 className="text-slate-500 text-sm font-medium mb-1">Target Database</h3>
                    <p className="text-slate-900 font-medium truncate" title={mdbPath}>eTimeTrackLite1.mdb</p>
                  </div>
                  <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
                    <h3 className="text-slate-500 text-sm font-medium mb-1">Sync Interval</h3>
                    <p className="text-slate-900 font-medium">Every 5 minutes</p>
                  </div>
                  <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl col-span-2">
                    <div className="flex items-center justify-between">
                      <div>
                        <h3 className="text-slate-500 text-sm font-medium mb-1">Next Sync</h3>
                        <p className="text-slate-900 font-medium">Pending auto-trigger</p>
                      </div>
                      <button 
                        onClick={() => StartSync()}
                        className="px-4 py-2 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 rounded-lg text-sm font-medium transition-colors shadow-sm"
                      >
                        Sync Now
                      </button>
                    </div>
                  </div>
                </div>

                <div className="mt-8 pt-6 border-t border-slate-100 flex justify-center">
                  <button onClick={() => setStep(1)} className="text-sm text-slate-400 hover:text-slate-600">
                    Reconfigure Relay
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
